name = "site-worker"
type = "webpack"
workers_dev = true

[site]
bucket = "./dist"
entry-point = "workers-site"

[env.production]
name = "site-worker-production"
route = "visheshbansal.dev/*"
vars = { BASE_URL = "https://visheshbansal.dev/" }