name = "site-worker"
type = "webpack"
account_id = "ca6dbf32f604acf91247340da7f3087d"
workers_dev = true

[site]
bucket = "./dist"
entry-point = "workers-site"

[env.production]
name = "site-worker-production"
route = "visheshbansal.ml/*"
vars = { BASE_URL = "https://visheshbansal.ml/" }