name = "site-worker"
type = "webpack"
workers_dev = true
compatibility_date = "2023-04-02"
main = "workers-site/index.js"

[site]
bucket = "./dist"

[env.production]
name = "site-worker-production"
route = "visheshbansal.dev/*"
vars = { BASE_URL = "https://visheshbansal.dev/" }