name: Create issue on dependabot pr
on:
- pull_request
jobs:
  create_commit:
    runs-on: ubuntu-latest
    steps:
    - name: Create issue using REST API
      if: contains(github.actor, 'dependabot')
      run: |
        curl --request POST \
        --url https://api.github.com/repos/${{ github.repository }}/issues \
        --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
        --header 'content-type: application/json' \
        --data '{
          "title": "Verify for any breaking changes in PR made by ${{ github.actor }}",
          "body": "- Kindly check if new dependencies are not introducing any breaking changes.\n- Ref: ${{ github.ref }}",
          "labels": ["dependencies", "good first issue"],
          "assignees": [""]
          }'
